medicalCosts/diseases/urls.py
from django.conf.urls import patterns, url
from diseases import views

urlpatterns = patterns('',
  url(r'^$', views.index, name='index'),
  url(r'^disease/(?P<disease_id>\d+)/$', views.disease, name='disease'),
  url(r'^add_disease/$', views.add_disease, name='add_disease'),
  url(r'^procedure/(?P<procedure_id>\d+)/$', views.procedure, name='procedure'),
  url(r'^operation/(?P<operation_id>\d+)/$', views.operation, name='operation'),
)

medicalCosts/medicalCosts/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from rest_framework import routers
from diseases import views


router = routers.DefaultRouter()
router.register(r'diseases', views.DiseaseViewSet)
router.register(r'procedures', views.ProcedureViewSet)
router.register(r'operations', views.OperationViewSet)


urlpatterns = patterns('',
    # Examples:
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include(router.urls)),
    #url(r'^$', 'medicalCosts.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^diseases/', include('diseases.urls', namespace='diseases')),
)

medicalCosts/diseases/models.py
from django.db import models
from django.forms import ModelForm
from django.utils import timezone

# Create your models here.
class Operation(models.Model):
  procedure = models.ForeignKey('Procedure')
  location = models.CharField(max_length=100)
  cost = models.PositiveIntegerField(default=0)
  date = models.DateTimeField(default=timezone.now(), blank=True)

class Procedure(models.Model):
  name = models.CharField(max_length=100)
  disease = models.ForeignKey('Disease')

  def __unicode__(self):
    return self.name

class Disease(models.Model):
  name = models.CharField(max_length=100)

  def __unicode__(self):
    return self.name

class DiseaseForm(ModelForm):
  class Meta:
    model = Disease
    fields = '__all__'

medicalCosts/diseases/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from diseases.models import Operation, Procedure, Disease

from rest_framework import viewsets
from diseases.serializers import DiseaseSerializer, ProcedureSerializer, OperationSerializer

def index(request):
  return render(request, 'diseases/index.html', { 'diseases': Disease.objects.order_by('name') })

def disease(request, disease_id):
  disease = get_object_or_404(Disease, pk=disease_id)
  return render(request, 'diseases/disease.html', {'disease': disease})

def add_disease(request):
  try:
    d = Disease.objects.get(name__iexact=request.POST['name'])
  except (KeyError):
    return render(request,
      'diseases/index.html',
      { 'diseases': Disease.objects.order_by('name'),
      'error_message': "Please enter a disease name." })
  except (Disease.DoesNotExist):
    d = Disease(name=request.POST['name'])
    d.save()
    return HttpResponseRedirect(reverse('diseases:disease', args=(d.id,)))
  else:
    return render(request,
      'diseases/index.html',
      { 'diseases': Disease.objects.order_by('name'),
      'error_message': "Please enter a unique disease name" })


def procedure(request, procedure_id):
  procedure = get_object_or_404(Procedure, pk=procedure_id)
  return render(request, 'diseases/procedure.html', {'procedure': procedure})

def operation(request, operation_id):
  operation = get_object_or_404(Operation, pk=operation_id)
  return render(request, 'diseases/operation.html', {'operation': operation})


class DiseaseViewSet(viewsets.ModelViewSet):
  """
  API endpoint that allows diseases to be viewed or edited.
  """
  queryset = Disease.objects.all()
  serializer_class = DiseaseSerializer


class ProcedureViewSet(viewsets.ModelViewSet):
  """
  API endpoint that allows procedures to be viewed or edited.
  """
  queryset = Procedure.objects.all()
  serializer_class = ProcedureSerializer

class OperationViewSet(viewsets.ModelViewSet):
  """
  API endpoint that allows operations to be viewed or edited.
  """
  queryset = Operation.objects.all()
  serializer_class = OperationSerializer

medicalCosts/medicalCosts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

# Create your views here.

def home(request):
  return render(request, 'medicalCosts/index.html')

medicalCosts/diseases/templates/diseases/disease.html
{% if disease %}
  <a href="{% url 'diseases:index' %}">Back to diseases</a>
  <ul>
  <li><a href="{% url 'diseases:disease' disease.id %}">{{ disease.name }}</a></li>
  <li>Procedures for disease</li>
  <ul>
  {% for procedure in disease.procedure_set.all %}
    <li><a href="{% url 'diseases:procedure' procedure.id %}">{{ procedure.name }}</a></li>
  {% endfor %}
  </ul>
  </ul>
{% else %}
  <p>This disease is unavailable.</p>
{% endif %}

medicalCosts/diseases/templates/diseases/index.html
<h2>Diseases</h2>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% if diseases %}
  <ul>
  {% for disease in diseases %}
    <li><a href="{% url 'diseases:disease' disease.id %}">{{ disease.name }}</a></li>
    <li>Procedures for disease</li>
    <ul>
    {% for procedure in disease.procedure_set.all %}
      <li><a href="{% url 'diseases:procedure' procedure.id %}">{{ procedure.name }}</a></li>
    {% endfor %}
    </ul>
    <br>
  {% endfor %}
  </ul>
{% else %}
  <p>No diseases are available.</p>
{% endif %}

<form action="{% url 'diseases:add_disease' %}" method="post">
  {% csrf_token %}
  Disease name:<br>
  <input type="text" name="name" required>
  <br><br>
  <input type="submit" value="Submit">
</form>

medicalCosts/diseases/templates/diseases/operation.html
{% if operation %}
  <a href="{% url 'diseases:operation' operation.id %}">Operation for: {{ operation.procedure }}</a>
  <ul>
  <li><a href="{% url 'diseases:operation' operation.id %}">{{ operation.location }}</a></li>
  <li><a href="{% url 'diseases:operation' operation.id %}">{{ operation.cost }}</a></li>
  <li><a href="{% url 'diseases:operation' operation.id %}">{{ operation.date }}</a></li>
  </ul>
{% else %}
  <p>This operation is unavailable.</p>
{% endif %}

medicalCosts/diseases/templates/diseases/procedure.html
{% if procedure %}
  <li>{{ procedure.name }}</li>
  <li>Operations for procedure</li>
  <ul>
  {% for operation in procedure.operation_set.all %}
    <br>
    <li><a href="{% url 'diseases:operation' operation.id %}">{{ operation.procedure }}</a></li>
    <li><a href="{% url 'diseases:operation' operation.id %}">{{ operation.location }}</a></li>
    <li><a href="{% url 'diseases:operation' operation.id %}">{{ operation.cost }}</a></li>
    <li><a href="{% url 'diseases:operation' operation.id %}">{{ operation.date }}</a></li>
    <br>
  {% endfor %}
  </ul>
{% else %}
  <p>This procedure is unavailable.</p>
{% endif %}

medicalCosts/diseases/templates/medicalCosts/index.html
diseases home